services:
  - type: web
    name: march8project
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn march8project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com,eight-march-hprn.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0 